project:
  type: website
  output-dir: _site
  render:
    - index.ipynb

website:
  title: "Aztec Prover Rewards Simulator"
  navbar:
    left:
      - text: Simulator
        href: index.html

format:
  html:
    page-layout: full
    toc: true
    code-fold: true
    code-tools: true
    theme: cosmo
    css: styles.css
    embed-resources: false

execute:
  enabled: true
  cache: false
  freeze: false
  warning: false
  error: false
